baseURL = "https://dropeo.github.io/"
footnoteReturnLinkContents = "â†©"
title = "Pedro Oliveira"
theme = "hallo"
defaultContentLanguage = "pt"

[permalinks]
    posts = "/:year/:month/:title/"
[Author]
    name = "Pedro Oliveira"
[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/dropeo"
    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"
