baseURL = "https://dropeo.github.io/othertest/"
footnoteReturnLinkContents = "â†©"
title = "Pedro Oliveira"
theme = "hallo"
defaultContentLanguage = "pt"

[permalinks]
    posts = "/:year/:month/:title/"
[Author]
    name = "Pedro Oliveira"
[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/dropeo"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:jpoliveira@id.uff.br"